### ISSUE TITLE
Improve install instructions

### ISSUE THREAD

**Issue by jhasse** [phocean/TopIcons-plus#1]
Hi!

I have problems installing this (don't know much about Gnome Shell extensions). I just moved the checked out version to the folder specified in the README, but the extension didn't show up in the GNOME Tweak Tool.

An install script would also be very nice :)

**Comment by phocean** [comment]
Done! Please test the new instructions and let me know if it works :-)

**Comment by jhasse** [comment]
Yes! Thank you very much, awesome extension :)
