### ISSUE TITLE
[Feature] Hidden/Collapsible 

### ISSUE THREAD

**Issue by codeman6100** [phocean/TopIcons-plus#10]
Personally I would love if there was an option to collapse all the icons into a single drop-down list.  I have between 5 and 7 icons active and they take up a large portion of panel space, which depending on screen resolution can become a problem.  Theoretically, if they could all be placed in a "sub-menu" then they would all still be visible if needed, but not take up space.

Thoughts?

**Comment by phocean** [comment]
Honestly, it would be better to make a whole different extension. I want to keep this one simple and easy to maintain.
And I want you to keep in mind that, first, the Gnome project should fix this mess, so that this kind of extension is useless.
