### ISSUE TITLE
Icon disappears in Activities view

### ISSUE THREAD

**Issue by orschiro** [phocean/TopIcons-plus#106]
Example:

Ksplice tray icon shows in normal mode but disappears in Activities mode. Tested on Ubuntu 18.04 daily build.

![image](https://user-images.githubusercontent.com/170947/33165459-3a167e72-d037-11e7-84b5-e584cb59f713.png)

![screenshot from 2017-11-23 10-15-42](https://user-images.githubusercontent.com/170947/33165475-4e949924-d037-11e7-8e0c-f353f4f64b14.png)

**Comment by orschiro** [comment]
Important to note that it doesn't always disappear. Not sure how to debug when and why it disappears in Activities mode.

**Comment by phocean** [comment]
I am quite confident that it has been fixed, at least I could not reproduce it.
Feel free to reopen if needed.
