### ISSUE TITLE
Makefile error in Freebsd

### ISSUE THREAD

**Issue by xfor19120101** [phocean/TopIcons-plus#109]
"cp -r --preserve=timestamps" in MakeFile is not support in Freebsd, use "cp -R -p" instead.
use "INSTALL_PATH = /usr/local/share/gnome-shell/extensions" 
tested in Freebsd 11.1 gnome.

**Comment by phocean** [comment]
Ok for `cp`.
No for the install path, I prefer it to be in the user path by default. You can easily change it for global install.

Thank you!
