### ISSUE TITLE
Icon size too small on hdpi screens

### ISSUE THREAD

**Issue by Jiehong** [phocean/TopIcons-plus#11]
Hello,

Could it be possible to add more size for the icons as 32 is the maximum, and seems a little small on hidpi screens?

Here is a screenshot at size 32 on a 2880×1800 display (192 dpi)

![size32](https://cloud.githubusercontent.com/assets/1061229/13187158/e9747b78-d749-11e5-87ac-b5150aeaba86.png)

You'll notice that it's also blurred (it's the battery, at the right of the keyboard icon, the keyboard icon and the rest are not related to this extension)

**Comment by phocean** [comment]
Sure, done. I was not aware of that with my small screen :-)
Now up to 512, should be enough.
