### ISSUE TITLE
[question] Can I add my own icons 

### ISSUE THREAD

**Issue by ensonb** [phocean/TopIcons-plus#110]
There is a Viber and SendAnythwre icon breaking the feng shui of my tray, can i add them? 
if yes then how?

thank you

**Comment by phocean** [comment]
No, it is not supported. I would recommend to look at this extension, along with env trick:

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74

It is a more modern way to achieve what has been removed from Gnome, I guess.
