### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by lviggiani** [phocean/TopIcons-plus#111]
Icons appears half size when HiDPI is enabled.
See this:
![screenshot](https://user-images.githubusercontent.com/139040/34996496-21276f3e-fada-11e7-9b3b-aacd287458f9.png)

And these are my screen settings:
![display](https://user-images.githubusercontent.com/139040/34996698-ae991cd2-fada-11e7-947b-1db253373a03.png)

I'm using latest version from git

**Comment by lviggiani** [comment]
I'm using latest version from GIT

**Comment by phocean** [comment]
This is more an issue for Skype and the way they packaged their app in Electron.
Such issues are common whatever desktop environment you are using.

In my experience, Electron apps work better with the libindicator API (as provided in Unity).

I encourage you to check and test this extension (using XDG_CURRENT_DESKTOP=Unity to launch your apps):

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74
