### ISSUE TITLE
it's not working in ubuntu 18.10

### ISSUE THREAD

**Issue by ghost** [phocean/TopIcons-plus#113]

**Comment by imliuruiqi** [comment]
That's right and it seems no one maintain this project.

**Comment by proski** [comment]
More generally, it's not working with GNOME 3.30. Should be addressed by PR #112.

**Comment by phocean** [comment]
I just merged #112, so it should be fixed now.

As I am not anymore a Gnome user, would someone be nice enough to `git pull` and test it?

**Comment by proski** [comment]
Working of Fedora 29 with GNOME 3.30 in Wayland mode. Pidgin shows the icon and remains running.

There is one annoyance though. Clicking on the Pidgin icon in the tray doesn't open Pidgin. I have to start it in GNOME Shell as if it's not running.

**Comment by proski** [comment]
A few more issues. If the tray horizontal alignment is Center, the Opacity settings is ignored. The icon is always shown at 100% opacity.

If the tray horizontal alignment is Right or Left, the icon is shown at the 100% opacity when the mouse cursor hovers over the top line of the icon. When the mouse cursor is over the rest of the is the icon, its appearance won't change (i.e. as if the mouse is not over the icon). I expect the icon to brighten in some way when the mouse cursor is over any part of the icon.

And the "best" part. The Pidgin window opens when I click on the top line of the icon, by not on any other part of the icon. It happens for any horizontal alignment.

**Comment by proski** [comment]
Another bizarre issue. Every time I change the tray offset in the preferences, the icon alternates between the 100% opacity and the configured opacity. But it's not solely a function of the tray offset. It it's 0 and I enter 2, the opacity changes. If it's 0 and I click `+` twice on the tray offset, the opacity changes twice, returning to the original value.

**Comment by phocean** [comment]
Then, I am going to close this issue as it is working.
For clarity, please open other issue for each kind of problem.
