### ISSUE TITLE
Stopped working in Gnome 3.30

### ISSUE THREAD

**Issue by alensiljak** [phocean/TopIcons-plus#114]
As reported in the comments on [Gnome Extensions site](https://extensions.gnome.org/extension/1031/topicons/), the extension does not work with Gnome 3.30+.

Fortunately, there is a simple fix, as reported by 0x3ax:
```
fix 3.30 ~/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:181 replace:
-tray.manage_screen(global.screen, Main.panel.actor); 
+tray.manage_screen(Main.panel.actor);
```

**Comment by phocean** [comment]
Isn't it a dupplicate of #113 ?
Some people reported that it is now working in 3.30. Have you tested the latest version from this repo ?

**Comment by mdkdir** [comment]
It's been fixed.

**Comment by phocean** [comment]
Thanks. I just released v22 and pushed it to the Gnome extension website.

**Comment by tannisroot** [comment]
Can you update the Gnome extension page to include versions 3.28 and 3.30? works great for me on those.
