### ISSUE TITLE
The icon disappears after unlocking

### ISSUE THREAD

**Issue by RMTT** [phocean/TopIcons-plus#119]
I am using gnome 3.32.0.When i unlocked my laptop,the previous icon disappeared.But the apps are still running.

**Comment by phocean** [comment]
How did you solve your issue?

**Comment by zhangkaizhao** [comment]
If you mean the case of session waken from idle, you can take a look at my recent hack:
https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons/commit/95916cab86ef7ae42809ff92386548129617038b .
I have tested on Arch Linux/GNOME 3.32 and FreeBSD 12/GNOME 3.28.
It works, though it is ugly and not perfect.

**Comment by RMTT** [comment]
> How did you solve your issue?

I'm so sorry that watch the reply too late.And i have no idea about this issue,i closed it because i already turn to the i3wm :).Good lucky to you.





> If you mean the case of session waken from idle, you can take a look at my recent hack:
> [zhangkaizhao/gnome-shell-extension-tray-icons@95916ca](https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons/commit/95916cab86ef7ae42809ff92386548129617038b) .
> I have tested on Arch Linux/GNOME 3.32 and FreeBSD 12/GNOME 3.28.
> It works, though it is ugly and not perfect.

I have already give up the gnome and turn to i3wm,so i can not test your hack,but thank you very much,good lucky to you. :)

**Comment by phocean** [comment]
> I'm so sorry that watch the reply too late.And i have no idea about this issue,i closed it because i already turn to the i3wm :).Good lucky to you.

A good choice that I understand, as I am myself not a Gnome user anymore (Mate, here).

Good luck!

**Comment by phocean** [comment]
@zhangkaizhao By the way, don't you feel ready to take over this repo?

I am not going to use Gnome again anytime soon, and even if I did, I would probably not use my own extension anyway.

I am willing to transfer it to an active contributor. It would be better for the community (to avoid confusion with yet another fork).

Just let me know...

**Comment by zhangkaizhao** [comment]
@phocean I understand your determination. Thank you very much for your contribution to this project.

I have tried Mate again after the high CPU usage issue and seems like Mate switches to appindicator now but it is not perfect yet, e.g. the pop-up menu of Dropbox has some issues.

I am writing this comment in Arch Linux/Budgie desktop 10.5 now. Budgie desktop is more lightweight and stabler.
