### ISSUE TITLE
Icons too small on HiDPI screens

### ISSUE THREAD

**Issue by juliandroid** [phocean/TopIcons-plus#12]
I'm using Arch Linux and Gnome 3.x with 4k monitor.
According to https://wiki.archlinux.org/index.php/HiDPI one can setup Gnome Shell with HiDPI screens by doing:

`$ gsettings set org.gnome.desktop.interface scaling-factor 2`

Which does decent job for ALL Gnome Shell GUI elements. Unfortunately the TopIcons-plus doesn't obey the "**scaling-factor**" setting, while the program's build-in options (like Size=32 and Padding=2) are not good enough. With the default icon sizes (24) is even worse.

I know that is not a blocker issue, but it will be great if you use the value of the **scaling-factor** (if exists) to scale the current value of the **Size** setting (and I guess the other geometrics). Please note, the scaling-factor is an integer value at this time.

![topicons](https://cloud.githubusercontent.com/assets/7766093/13380367/e8c7d8bc-de49-11e5-9dcb-5e3b6d59d840.png)

Please take a look at the screenshot and do a visual comparison of the "package manager" and skype icons to the system's icons like Network, Sound and Clipboard icons! Keep in mind that the TopIcons Size is set to the maximum of 32.

**Comment by juliandroid** [comment]
Even if you have a low-res screen you can test the lack of proportions by running the:

`$ gsettings set org.gnome.desktop.interface scaling-factor 2`

and later return it to the default:

`$ gsettings reset org.gnome.desktop.interface scaling-factor`

As workaround I can use c1507ab but still following the recommended way of using **scaling-factor** is future proof.

**Comment by juliandroid** [comment]
Please reopen the ticket since it's not completely fixed. I'm copying the rest from the "conversation" thread.

The default settings for the Icon Size and Icon Padding is 24 and 6 respectively. Take a look at the first screen shot for the result:
![topicons_24_6](https://cloud.githubusercontent.com/assets/7766093/13548779/eb0d1752-e300-11e5-8500-bdd5276c2555.png)
Intentionally I have added red grid (with Gimp) over the screenshot for better alignment with the "system" icons.
Unfortunately the (obviously) bigger "Software Update" icon is misaligned and cropped both from bottom and right! Moreover the 24 size (24 x 2 scale factor) as default looks too big. I guess the outer container should be both somewhat vertically and horizontally centred?

The second screenshot is with Icon size 16 (also multiplied by 2x factor scale) match the "system" icons size, but then look how "Software Update" icon is cropped from all sides!
![topicons_16_6](https://cloud.githubusercontent.com/assets/7766093/13548828/bf5078f6-e301-11e5-871d-55d2b3d5df7b.png)

I'm not sure I fully understand why in the first case there is misalignment and in the second case why the icons are not exactly scaled but rather cropped!? I guess there is something small missing.

Please note, that I have use Antergos flavor of Arch Linux with "Adwaita (default)" GTK+ theme, "Gnome" icons and "Default" Shell theme - this might matter, but I think the problem is not related to exact themes!

Also don't forget to run: Alt+F2 and then "r" command to restart the Gnome Shell, since just relying to automatic update after changing the Icon Size and Icon Padding from the TopIcons settings is **not** enough!

**Comment by juliandroid** [comment]
Btw, when I mentioned the used themes from my side (mostly default for my distro), what I'm saying there, is that even if the "system" icons features different default sizes (in my case they are 16px x scale factor of 2 = 32px) from what you have on your system, they should be properly scaled and aligned. Even if you like 24px instead of 16px - in both cases, more or less they should be properly scaled :)

**Comment by phocean** [comment]
Ok, I will look at it when I have time.
I started this extension as a simple fork with a few extra features, but I know it needs a complete rewrite anyway.
But for that, I need time (or/and the good documentation that the Gnome project is unable to provide), so keep wired and be patient.

**Comment by phocean** [comment]
Hi,

The last dev branch is an attempt to handle it more or less correctly. It is not perfect (some apps don't handle it well anyway, like Dropbox or Gnome-Encfs) but before going on I would like to have a feedback from a real environment (remember, I don't have a HDPI screen).

Testing:

```
git pull
git checkout dev
make
```

I probably broke some stuff while testing and I plan to rewrite things later. After testing, you should go back to the stable version:

```
git checkout master
make
```

And reload Gnome.

So please let me know if it is better.

**Comment by phocean** [comment]
By the way, here is how it looks like on my system:

![capture d ecran de 2016-03-26 18-23-07](https://cloud.githubusercontent.com/assets/4280885/14061414/f0dda784-f37f-11e5-8472-31def689d0ca.png)

**Comment by juliandroid** [comment]
Thanks!
It is definitely an improvement! Now I don't see that cropping anymore and also I don't see that weird scaling.

![topicon](https://cloud.githubusercontent.com/assets/7766093/14061945/ceada1a2-f396-11e5-826e-a51975f0cbcb.png)

The Software Update icons ( https://github.com/manjaro/pamac/tree/master/data/icons/24x24/status ) looks great, but the Skype icon is small. Sure, all those edge cases should be debugged and figured it out the problem.

Btw, the Size doesn't seems to work anymore and the Padding option is somewhat inconsistent.

**Comment by phocean** [comment]
> Btw, the Size doesn't seems to work anymore and the Padding option is somewhat inconsistent.

Sure, I will have to refactor them for the next version. Thanks for this feedback !
