### ISSUE TITLE
Icons don't darken with gnome pop-ups

### ISSUE THREAD

**Issue by marioortizmanero** [phocean/TopIcons-plus#124]
When gnome opens a pop up, like when you install a new extension, the rest of the screen darkens... Except for the icons from this extension.

![Example](https://i.imgur.com/1tK5l2Q.png)

**Comment by phocean** [comment]
I cannot reproduce it. Have you tested without the dash to panel extension ?

**Comment by marioortizmanero** [comment]
Hey, sorry but I don't use Gnome anymore so I can't test it myself. You can either try yourself with MEGASync (perhaps it was only that program), or close this.

Thanks!

**Comment by phocean** [comment]
No problem, thank you ;)

Thus I am closing it for now.
