### ISSUE TITLE
Extension disable after screen is locked

### ISSUE THREAD

**Issue by ghost** [phocean/TopIcons-plus#13]
There seems to be a problem when unlocking the screen after locking it. The tray icons back to the original position (extension disable), To reactivate the extension must restart the gnome-shell. A similar issue was happening with the Top Icon extension back a few of years ago.

I use Gnome 3.18.2

**Comment by phocean** [comment]
I never had such an issue (of course, I lock/unlock my screen all the time).
It looks like a severe crash in your case.

Please check the log when it crashes and send me the output:

`journalctl -xn -f /usr/bin/gnome-shell`

Also, what are the programs loaded in your tray? Your distro ?

**Comment by phocean** [comment]
Close, please reopen if you even bring up debug info.
