### ISSUE TITLE
Detecting if TopIcons-Plus is active

### ISSUE THREAD

**Issue by davidbannon** [phocean/TopIcons-plus#134]
Anyone aware of a way to detect if Topicons-plus is active, from another application ?

I make a thing called tomboy-ng and we depend on TopIcons-plus to display our System Tray Icon on Gnome desktops. But if TopIcons-plus is not installed and 'on', the end user does not have any ability to interact with the app. So, I'd like to test to see if LibAppIndicator3 is available (easy) and TopIcons-plus (unknown).
Thoughts anyone ?
Davo

**Comment by jubalh** [comment]
You will probably need to check in all available config files. Like `~/.config/gtk-3.0/settings.ini`.
Maybe also [dconf](https://wiki.gnome.org/action/show/Projects/dconf?action=show&redirect=dconf).

Why do  you depend on Topicons-Plus for your application to work? You use one of it's icons? You could check the license and include that specific icon in your application.

**Comment by parkerlreed** [comment]
I assume they have an application that needs the system tray.

**Comment by davidbannon** [comment]
Yes indeed. App is built using FPC and Lazarus (ie Pascal). And right now, for System Tray Icons, all that can do is the old System Tray model or the Unity inspired LibAppIndicator3.  Works fine with TopIconsPlus installed (and many thanks for that !) but of course fails silently if its not there.

Thanks, I will look into the ideas mentioned and report back.....

Yep, dconf is the answer -
dconf /org/gnome/shell/
....  'TopIcons@phocean.net' ....

Thanks indeed !
Davo
