### ISSUE TITLE
Request: Support for GNOME 3.36

### ISSUE THREAD

**Issue by Scotty-Trees** [phocean/TopIcons-plus#139]
GNOME 3.36 is going to be released March 11 and I like your extension very much and hope it can be updated to include support for GNOME 3.36. Keep up the great work!

**Comment by xz-dev** [comment]
It is still available in GNOME 3.36.0

**Comment by teaper** [comment]
gnome 3.36中图标显示异常  
![Screenshot from 2020-03-15 14-26-55.png](http://ww1.sinaimg.cn/large/006kWbIogy1gculh29zbqj303w00tt8j.jpg)

**Comment by pavethem** [comment]
Basically the icons are way too big under Gnome 3.35
Here's Unity Hub and Deluge
![topicons](https://user-images.githubusercontent.com/847563/76701923-dbc60680-66c5-11ea-8da3-dd8e15f34b1f.png)

**Comment by tannisroot** [comment]
Same issue here, and making them smaller through configuration doesn't have any affect.

**Comment by sentakuhm** [comment]
confirm same issue here too.

**Comment by rinaldus** [comment]
I confirm it too.
![Снимок экрана от 2020-03-27 14-57-06](https://user-images.githubusercontent.com/1160332/77753906-6cdc9c00-703b-11ea-92dd-24d7df05447d.png)

**Comment by abougouffa** [comment]
I have the same issue too,

**Comment by rinaldus** [comment]
"Unite" extension with the same functionality [fixed](https://github.com/hardpixel/unite-shell/commit/acd7e420c8b36e264b54cd9a392405345fcfab33) incorrect size of tray icons. I installed it instead of this extension, because this extension looks like dead, there's no response from author since 3 weeks.

**Comment by vancez** [comment]
> "Unite" extension with the same functionality [fixed](https://github.com/hardpixel/unite-shell/commit/acd7e420c8b36e264b54cd9a392405345fcfab33) incorrect size of tray icons. I installed it instead of this extension, because this extension looks like dead, there's no response from author since 3 weeks.

https://github.com/vancez/TopIcons-plus/commit/edd45586ddb3b474f9c7293df42772a298b1afb1

**Comment by phocean** [comment]
It should be fixed thanks to #142 .
Could you please confirm ?
I am closing it meanwhile.
