### ISSUE TITLE
Icons not resizing properly anymore in Gnome 3.36

### ISSUE THREAD

**Issue by artscoop** [phocean/TopIcons-plus#141]
Hi,
They changed yet another thing in Gnome 3.36, so that now, tray icons are not resized anymore in TopIcons. Well, the client area is properly resized, but the icon size doesn't adapt, so it's just cropped.
Meanwhile, all other controls keep working properly: contrast, lum, opacity, desat etc.

**Comment by TR4SPY** [comment]
Have the same issue, also posted it in comments section on Gnome extension site but still no response or update.

**Comment by phocean** [comment]
Thanks for the report. I don't have 3.36 yet so I can really test or work on it for now.
Probably again an API breakage.

**Comment by hmasmoudi** [comment]
Hi, Nomally fixed by commit: (#142) edd45586ddb3b474f9c7293df42772a298b1afb1

**Comment by phocean** [comment]
Ok, thanks for the info.

I prefer to close it, feel free to re-open if necessary.
