### ISSUE TITLE
Click Settings error

### ISSUE THREAD

**Issue by Wings-Fantasy** [phocean/TopIcons-plus#144]
Gnome Shell 3.30.2 for Debian 10
I downloaded this extension at "https://extensions.gnome.org/extension/1031/topicons/" and reported an error.
When opening the settings interface, it reports: `Error: Schema org.gnome.shell.extensions.topicons could not be found for extension TopIcons@phocean.net. Please check your installation.`
How should I resolve this issue?

**Comment by ZayRTun** [comment]
I just updated this extension and I am getting the same error as above.

```
Error: Schema org.gnome.shell.extensions.topicons could not be found for extension TopIcons@phocean.net. Please check your installation.

Stack trace:
  getSettings@/home/zay/.local/share/gnome-shell/extensions/TopIcons@phocean.net/convenience.js:88:15
  TopIconsPlusSettings<._init@/home/zay/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:28:26
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/zay/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:183:19
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  ```

**Comment by Cyber-Oto** [comment]
I have also just updated on Manjaro 19.0.2 with GNOME 3.36.0.1 and got error

The settings of extension TopIcons@phocean.net had an error:
```
Error: Schema org.gnome.shell.extensions.topicons could not be found for extension TopIcons@phocean.net. Please check your installation.
```

Stack trace:
```
getSettings@/home/user/.local/share/gnome-shell/extensions/TopIcons@phocean.net/convenience.js:88:15
_init@/home/user/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:28:38
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:183:19
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by isality** [comment]
+1 after updated

ubuntu 18.04.4

**Comment by kotbullar** [comment]
EDIT: solved by manually include schemas folder for getsetting procedure. 



+2 
debian 10 buster



```
Error: Schema org.gnome.shell.extensions.topicons could not be found for extension TopIcons@phocean.net. Please check your installation.

Stack trace:
  getSettings@/home/ric/.local/share/gnome-shell/extensions/TopIcons@phocean.net/convenience.js:88:15
  _init@/home/ric/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:28:26
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/ric/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:183:19
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
```

**Comment by Cyber-Oto** [comment]
After today's update via https://extensions.gnome.org/extension/1031/topicons/ all works OK for me.

Keep up the good work!

**Comment by phocean** [comment]
Sorry, my mistake, and yes it has been fixed! :-)

**Comment by erciccione** [comment]
Still broken for me (Debian Buster)

**Comment by phocean** [comment]
@erciccione with the same error message, that's not possible.

All versions running on the Gnome website have the missing "schemas" files:

version 22 is for Gnome <= 3.30 and version 26 for Gnome >= 3.32.

Please uninstall/reinstall completely.
If it still does not work, please check well the error message.

**Comment by erciccione** [comment]
@phocean Not the same error message. No message at all actually, simply no icons showing up.

I already reinstalled with no success. Should i open a new issue?

**Comment by phocean** [comment]
@erciccione Debian Buster is Gnome 22, right?

To make things sure, you installed it from the Gnome website,.not this repo?

I have to try and reproduce the problem, it's very strange.

**Comment by erciccione** [comment]
> Buster is Gnome 22, right?

[Gnome 30](https://packages.debian.org/buster/gnome-shell)

> To make things sure, you installed it from the Gnome website,.not this repo?

Correct, i installed it long ago using Gnome extensions. It broke after the update as reported in this issue. Note that after the latest upgrade (which fixed the problem for @Cyber-Oto) i don't see any warning. The extension result correctlyinstalled, but no icons are showing up.

**Comment by phocean** [comment]
@erciccione I understood the issue.

Actually, the Gnome website is not working exactly as I expected, and not as it should IMHO:

- it installs the latest version of the extension, whatever your gnome-shell version is and the metadata that I set in the extension ;
- the metadata are just being used to show you that menu to select a version *only* for manual installation.

So, you have to download manually the extension version 22, unzip it and `make install`.

Meanwhile, I will try to figure it out with git tagging and probably inciting people to rather use github...

It's clearly a mess!

**Comment by erciccione** [comment]
Thank you for looking into it @phocean, i will install it from the repo.

**Comment by phocean** [comment]
@erciccione You are welcome ;)

I just updated the releases:

https://github.com/phocean/TopIcons-plus/releases

You will want to install version 22.

Another issue would have to be created for better tracking, should you have any other problem.
