### ISSUE TITLE
debian 10.3 update fail

### ISSUE THREAD

**Issue by sacredland** [phocean/TopIcons-plus#146]
since i updated from extensions.gnome.org i have lost all tray icon, like hexchat. not working anymore.

**Comment by phocean** [comment]
what is the version of Gnome there?

**Comment by sacredland** [comment]
3.30.2 .. i have unistall/reinstall, alt-f2 -> r .. nothing neither, close/reopen hexchat, does nothing, like if it wasnt load.

**Comment by phocean** [comment]
Please try again.

I made a typo in supported versions, which I just fixed.
The website should not have proposed the update to your gnome version.
So, for 3.30, you should stay on version 22.

Let me know how it is now.

**Comment by sacredland** [comment]
problem fixed. thanks for you wonderful work and continue it: it is very useful to have tray inco (even if gnome coder said it's useless)

**Comment by phocean** [comment]
Thank you @sacredland ! :love_you_gesture:
