### ISSUE TITLE
Tag version 23

### ISSUE THREAD

**Issue by stephanlachnit** [phocean/TopIcons-plus#148]
Looks like version v23 was created at 3d4a5a8ae05380faf52aae63c228b3cdec337128, but there is not git tag yet. Please add a git tag, as github automatically creates a tarball which can be used in distributions.
Also btw the `22` tag should be removed since there is already a `v22` tag.

**Comment by phocean** [comment]
I will, thanks.

**Comment by phocean** [comment]
By the way, it should help with cases like #144 .

**Comment by phocean** [comment]
This is done: https://github.com/phocean/TopIcons-plus/releases

It's a little mess due to version skipping and several breakages in GTK, but that should ok...
