### ISSUE TITLE
Indicator menu shows boxes instead of letters

### ISSUE THREAD

**Issue by seahindeniz** [phocean/TopIcons-plus#149]
Indicator right click menu shows me non letter characters instead of actual words

Steps to Reproduce:
- Open Discord and wait for indicator to be shown
- Right click on indicator
- See options

Expected Result:
It should show actual texts

Actual Result:
It shows non letter boxes

![image](https://user-images.githubusercontent.com/5789670/80404714-4031d380-88ca-11ea-9bfe-b5e12b93af2e.png)

Ubuntu 18.04.4

**Comment by phocean** [comment]
Probably missing fonts and not in the scope of the extension.

Such menus are managed by the app, there is no possibility for the extension to influence it.

**Comment by seahindeniz** [comment]
Is there any way to debug this issue to see which font is missing? @phocean
