### ISSUE TITLE
load after updating gnome

### ISSUE THREAD

**Issue by wasrek404** [phocean/TopIcons-plus#15]
After each installation of updates on my machine (I am running Arch so that is quite a lot) I have to reinstall the etension from the Gnome Shell extensions website. Is it possible to just compile the source and copy the bin to the correct folder at each login? This would prevent that I'd have to turn it on each time gnome is installed. 

Thanks in advance!

**Comment by phocean** [comment]
What do you mean by compiling and bin folder? It can't be done with extensions.
The extension is placed where it should be, i.e in ~/.local/share/gnome-shell/extensions/.

**Comment by wasrek404** [comment]
I find it quite annoying atm that with each update the tray icon at the bottom left inside gnome returns and topicons is removed or uninstalled. I want a way to enable the extension and carry it over to the next update (each time) of gnome. You have any suggestions for this?

**Comment by phocean** [comment]
Clearly, no. I understand and agree with your feeling, but extension developers cannot do anything more than compelling with Gnome API.
You should report such enhancement suggestions to the Gnome project itself.
But don't expect much, sadly, they are not known to care much about user feedback (thus, this extension).
