### ISSUE TITLE
separator-left is null

### ISSUE THREAD

**Issue by lucazade** [phocean/TopIcons-plus#16]
I still get 'separator-left is null'...  it seems a race condition when the gnome session is opening on a slow pc.
I'm using latest commit on archlinux and gnome 3.18.

If I raise this from 2500 to 5000 it seems better:
`onTrayIconAdded(o, icon, role, 5000);`

interesting log:
`(gnome-shell:1528): St-WARNING **: length values must specify a unit
mar 26 05:57:49 archos gnome-session[1469]: (gnome-shell:1528): St-WARNING **: length values must specify a unit
mar 26 05:57:49 archos gnome-session[1469]: Gjs-Message: JS LOG: Extension "TopIcons@phocean.net" had error: TypeError: separatorLeft is null
mar 26 05:57:49 archos gnome-session[1469]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Vertex-Mod/gnome-shell/gnome-shell.css
mar 26 05:57:50 archos gnome-session[1469]: Gjs-Message: JS LOG: Extension "TopIcons@phocean.net" had error: TypeError: separatorLeft is null
mar 26 05:57:50 archos gnome-session[1469]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Vertex-Mod/gnome-shell/gnome-shell.css
mar 26 05:57:50 archos gnome-session[1469]: Gjs-Message: JS LOG: Extension "TopIcons@phocean.net" had error: TypeError: separatorLeft is null
mar 26 05:57:50 archos gnome-session[1469]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Vertex-Mod/gnome-shell/gnome-shell.css
mar 26 05:57:50 archos gnome-session[1469]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Vertex-Mod/gnome-shell/gnome-shell.css
mar 26 05:57:50 archos gnome-session[1469]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Vertex-Mod/gnome-shell/gnome-shell.css
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:293
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:293
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:293
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:293
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:293
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshSaturation@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:264
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshSaturation@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:264
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshSaturation@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:264
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshSaturation@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:264
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
mar 26 05:57:51 archos gnome-session[1469]: (gnome-shell:1528): Gjs-WARNING **: JS ERROR: TypeError: separatorLeft is null
mar 26 05:57:51 archos gnome-session[1469]: moveToTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:180
mar 26 05:57:51 archos gnome-session[1469]: refreshTray@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:275
mar 26 05:57:51 archos gnome-session[1469]: refreshPos@/usr/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:296
`

**Comment by phocean** [comment]
I added a sanity check on the dev branch, as a loop. It seems there is no side impact, but I am not totally confident. As I cannot reproduce the issue, could you please test it for me:
https://github.com/phocean/TopIcons-plus/blob/dev/extension.js

To get it:

```
git pull
git checkout dev
make
```

And of course reload Gnome.

**Comment by lucazade** [comment]
ok.. thanks for the commit!
let me try it a bit because the issue was not always present.

**Comment by lucazade** [comment]
unfortuately the issue is still here.. still random..
at the moment the only workaround I found is to comment any separatorLeft in the code :)

**Comment by phocean** [comment]
Only at session opening, right ? What are the other extensions that you use, just in case ?

**Comment by lucazade** [comment]
only at session opening.. these are the extensions i'm using: bottompanel, flippery move clock, sound devide chooser, taskbar and topicons.
In the tray are loaded from the startup dropbox and owncloud

**Comment by lucazade** [comment]
![schermata da 2016-03-27 12-28-13](https://cloud.githubusercontent.com/assets/1557010/14064984/69abd842-f417-11e5-8460-d37d51270733.png)
this is how the desktop look like.. i need all these extensions because of gnome lack of customizations!

**Comment by phocean** [comment]
Hi,
Once again, I would recommend you to try out the latest version (from here).

I forgot but with the recent changes (2 weeks ago or so), there is no more an individual container for each icon, but a box layout for all of them.

So, in other words, there is no more "separator" and your issue should be definitely solved!
Otherwise, that's black magic :-)
