### ISSUE TITLE
Doesn't play well with Wayland

### ISSUE THREAD

**Issue by marcolaux** [phocean/TopIcons-plus#17]
Hi there,

if you chose Wayland as a session it's only possible to click the icon at the outer corner.
Sadly it's nearly unusable under Wayland. The old TopIcons extension works fine though.

All the best

**Comment by phocean** [comment]
Sorry for the late response and thanks for notifying. It definitely has not been tested on Wayland yet.
I will work on that next.

**Comment by phocean** [comment]
No wonder, I recently learned that Gnome / Wayland is not going to support status icons.
See : https://wiki.gnome.org/Design/Whiteboards/StatusIcons

So this is not issue with TopIcons and there is nothing I can do to help. Feel free to make voice against the Gnome project (I sometimes do) ;-)
