### ISSUE TITLE
copyright and licensing information missing

### ISSUE THREAD

**Issue by smcv** [phocean/TopIcons-plus#19]
Hi,
I would like to package this extension in Debian. Unfortunately, it doesn't come with any copyright or licensing information. If you can contact the copyright holders for permission, it would be great to license it under GPL-2+ , LGPL-2+ or a permissive license.

I suspect that all the contributors, including the contributors to @mjnaderi's earlier fork, are probably copyright holders.

Do you have any contact details for "ag", the original author?

**Comment by phocean** [comment]
In my opinion, knowing from where I picked up some code from, ag would be the only legitimate copyright holder (and I for a few add-ons).

That said, I am not a licensing expect and I don't care much, but, aren't any  gtk work implicitly licensed as LGPL?

Unfortunately, I have no contact and don't know how to reach him.
The absence of maintainance and the fact that his website is not answering were my main motivation to fork.

**Comment by phocean** [comment]
Oh, and before you spend time packaging it, are you aware that Gnome is going to obsolete the concept of tray with Wayland?

**Comment by smcv** [comment]
> aren't any gtk work implicitly licensed as LGPL?

As far as I understand copyright law, your extension probably isn't considered to be a derivative work of GTK or gnome-shell.

I think I've found an email address for `ag`, so I'll try to contact all the potential copyright holders by email.

I would recommend either "GPL v2 or any later version" like gnome-shell, or the very permissive 3-clause BSD license that's used in convenience.js. Do you have any preference between those?

**Comment by phocean** [comment]
I feel like doing what is the closest to the Gnome project, so I would say GPL v2.
Let me know if I can help you in any way.

EDIT: I just added the licence to the repo. Not sure if this is the right way to do but I will make some changes if necessary.

**Comment by phocean** [comment]
I just found this while I was going to push my extension there:

https://extensions.gnome.org/upload/

You need to agree with this when you upload your extension there:

>  I verify that my extension can be distributed under the terms of the GPLv2+

So, no more issue I guess. It was explicitly GPLv2+ and will stay under this license.

**Comment by smcv** [comment]
> So, no more issue I guess. It was explicitly GPLv2+ and will stay under this license.

Aha, great. So aq and @mjanaderi must have already given permission to license it under GPLv2+, because otherwise they couldn't have uploaded it to extensions.gnome.org. That's good to know.
