### ISSUE TITLE
Too much padding

### ISSUE THREAD

**Issue by pezz** [phocean/TopIcons-plus#23]
Hi there,

I just updated my extensions tonight, and the metadata says I'm on version 10 now.

There seems to be a lot of additional space even with padding set to 0.

https://i.imgur.com/DMxtKhQ.png

The older version I had been running didn't look like this.

Cheers.

**Comment by phocean** [comment]
Hi,

If you are on version 10, then you are not on the latest version. Please use the github version along with its installation script.
Note that the gnome website takes a lot of time before validating submitted versions. Version 11 was submitted two weeks ago, and version 12 just yesterday.

So I close this bug report as invalid, just reopen if you are still unhappy with version 12, but it is unlikely.

**Comment by pezz** [comment]
Ah, no worries.

Yes, I updated via extensions.gnome.org - I'll stick with this until version 12 appears on there, as it's very convenient.

It's not a deal-breaker.

Cheers for the response mate.

**Comment by pezz** [comment]
Now on version 12 as e.g.o has updated.

Still have the excess padding. :(
