### ISSUE TITLE
support for 3.10 ?

### ISSUE THREAD

**Issue by schlichtanders** [phocean/TopIcons-plus#27]
Gnome 3.10 is currently the default gnome for Ubuntu 14.04. ...
it seems not working here, any plans/ideas?

**Comment by phocean** [comment]
It is just that I have no platform to test it, but there are chances it works.
Edit metadata.json, and just add 3.10 like this:

```
  "shell-version": [
    "3.10", "3.16", "3.18", "3.20"
  ],·
```

Let me know if it works, along with a screenshot, and I would update the file for everybody.

Thanks! :-)

**Comment by schlichtanders** [comment]
I just tested, what you said and get a warning triangle with tooltip `error loading extension` at gnome-tweaks (where it is listed under the "Topicons plus")

I changed the line in the extension folder as you said, and even restarted the machine to be sure...
any ideas?
![topicons plus not loadable](https://cloud.githubusercontent.com/assets/4255480/16171252/727951ae-356a-11e6-8248-1e43f931dfba.png)

**Comment by phocean** [comment]
You did it right, I think, so it is not good news.
Could you post the errors (for today) in the logs:

```
journalctl /usr/bin/gnome-shell
```

**Comment by schlichtanders** [comment]
it seems don't have journalctl and I cannot find it either...
(maybe its because I have a bodhi ubuntu where I installed a separate gnome-shell, on 14.04, here it says that for 14.04. there is no journalctl unfortunately... I am not sure...
http://askubuntu.com/questions/617290/how-to-read-systemd-journal-file-on-system-that-has-no-systemd)

**Comment by phocean** [comment]
Sorry but I have no idea then where Ubuntu stores the logs for this version.
As Ubuntu 14.04 does not have systemd/journalctl, the logs must be in a flat file somewhere in /var/log, but that's all I can tell. It has been ages since I last tried Ubuntu.
Try to get this information to an Ubuntu forum.

**Comment by schlichtanders** [comment]
Thanks for responding. As my time is a bit sparse, i will rather Switch to
an OS with a supported Gnome version ;-)

Thanks again very much for responding so quickly,
Best,
Stephan

**Comment by phocean** [comment]
You are welcome :-)
I was hesitant to tell it to you, because after all this Ubuntu version is still supported, but I was thinking it loud.
You will benefit from many improvements switching to a more recent version, like Ubuntu 16.04, OpenSUSE (my distro) or Fedora, so it is worth updating.
