### ISSUE TITLE
Didn't work with gnome 3.20 on fedora 24.

### ISSUE THREAD

**Issue by zubrzubr** [phocean/TopIcons-plus#29]
Hello. I'm tried this extensions on my system (gnome 3.20 / fedora 24) and looks like it doesn't work. Bottom tray disappears but no changes on top. Please help to fix.

**Comment by shihrer** [comment]
Latest update stopped working for me as well on Ubuntu Gnome.  Running Gnome 3.18.

**Comment by phocean** [comment]
Hello,
I had no problem on my test machines, but now I can reproduce the problem on Fedora 24. You can actually get it to appear by reload Gnome-Shell with alt-F2 and then "r".
But of course, this is not normal. I am investigating.

**Comment by phocean** [comment]
Note: rolled-back the version on https://extensions.gnome.org/extension/1031/topicons/, to avoid more trouble to users.

**Comment by zubrzubr** [comment]
Hi again. I'm using fedora 24 with wayland session. I'm tried to logout and login back but still have issue. Reload also didn't help me.
PS. On my laptop with ubuntu gnome 16.04 works well.

**Comment by phocean** [comment]
It seems that you cannot reload Gnome under Wayland, it has not been supported yet. I got a fresh virtual machine and it refuses to reload with "not available yet".
Anyway, under Wayland, the extension also works fine for me. I had reproduced the problems only under X after first launch, and then reload made it work.
Please try with the github version, and any other extension disabled.
It seems it going to be hard as hell to track down. :-(

**Comment by phocean** [comment]
Also right after login (with the extension enabled):

```
% journalctl /usr/bin/gnome-shell -n 200 > log.txt
```

At this time, I am not able to reproduce the problem anymore...

**Comment by zubrzubr** [comment]
Strange but it still reproducible form me.

```
Jul 10 18:22:32 localhost.localdomain org.gnome.Shell.desktop[1574]: (gnome-shell:1574): Gjs-WARNING **: JS ERROR: ReferenceError: wmClass is not defined
Jul 10 18:22:32 localhost.localdomain org.gnome.Shell.desktop[1574]: onTrayIconAdded@/home/zubr/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:92
Jul 10 18:22:32 localhost.localdomain org.gnome.Shell.desktop[1574]: moveToTop@/home/zubr/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:167
```

**Comment by zubrzubr** [comment]
Installed from git repo.

**Comment by phocean** [comment]
Ok, I just fixed the warning, it was my mistake.
However, I doubt it is causing all that trouble. Anyway, please:

```
git pull
make install
```

And test again.

Also, please make sure that the log is complete, because it is not much (there might be some other glib / gtk errors).

**Comment by zubrzubr** [comment]
I just put warning only about top-icon-plus. Let me reinstall it again.

**Comment by zubrzubr** [comment]
UPD. Last changes help me.
1. Pulled your changes.
2. Logout and login.
3. Then enable extension without relogin and it works fine.
Thank you very much.

**Comment by phocean** [comment]
So that was it!  I am relieved that was so simple.
It is really not helpful that different versions of Gnome behave differently.

Anyway, thank you for your report and helping me! :-)
I am pushing the fixed version to the Gnome web site, but it will be pending validation a few days.

**Comment by shihrer** [comment]
Git version working for me as well.  Thanks for the quick fix.

**Comment by phocean** [comment]
Good news!
I now have finished to install a bunch of VM with major distros (Ubuntu 16.04, Fedora 24, OpenSUSE Tumbleweed) so that I can do more testing for the next releases.

**Comment by shihrer** [comment]
Just wondering, will I have to manually remove the git version once the extensions.gnome.org version gets updated?

**Comment by phocean** [comment]
No, the update would overwrite files, which are in  `~/.local/share/gnome-shell/extensions`.

.

**Comment by shihrer** [comment]
OK awesome, thanks again.
