### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by sojusnik** [phocean/TopIcons-plus#3]
Hi!

Thanks for creating this useful extension!

Do you thought about adding an option to **completely** desaturate the icons to fit the greyish indicator items of Gnome?

For reasons of consistency the space between the icons should also be adjustable, if that's possible at all. At the moment they are placed too tightly together in comparison with the normal indicator icons. By increasing the icon size in the options of the extension the space gets wider, but so are some of the icons.

Cheers!

**Comment by phocean** [comment]
Hi,

Thanks, these suggestions are good and can be implemented without much pain.
However, I have other issues and priorities at the moment, so please be patient :-)

**Comment by phocean** [comment]
Done in the last release, even though I should improve the code in the future.
