### ISSUE TITLE
Update published on extensions.gnome.org on July 11 breaks extension

### ISSUE THREAD

**Issue by ronjouch** [phocean/TopIcons-plus#30]
**Before**: extension used to work for a long time

Updated it through extensions.gnome.org on July 11

**Now**: extension seems to start (the bottom left tray is hidden) and no error is shown in GNOME Tweak Tool, but no icon (for me: Dropbox, Skype) is moved to the top-right panel

Using GNOME Shell 3.20.3 under Arch Linux, feel free to ask for more debug info.

**Comment by phocean** [comment]
See #29, problem fixed.
The problem now is the time Gnome will take to validate the update on their website, I have no control on it. Their process is flawed.
That is why I encourage to use the github version.
