### ISSUE TITLE
After update no tray icons anymore

### ISSUE THREAD

**Issue by paddyesch** [phocean/TopIcons-plus#31]
I updated to the latest version on extensions.gnome.org and after the update the tray icons are gone. I had the tray icon of SpiderOak before the update and now it's gone. If I deactivate TopIcons I see the SpiderOak tray in the bottom left area (default). Maybe there went something wrong with the update? I'm using Fedora 24 with GNOME Shell 3.20.3. THX!

**Comment by phocean** [comment]
Sorry but see #29 and #30. Please use the version from github.
