### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by smcv** [phocean/TopIcons-plus#32]
I'm about to make this extension available in Debian, under the name `gnome-shell-extension-top-icons-plus`. It would be helpful for our automated monitoring if you could tag version 15 and each new release after that with `git tag`, and push those tags to this repository.

Ideally, please tag each version that you consider to be ready for general use (the ones you release to extensions.gnome.org), but not intermediate development commits - that way I can make sure to only upload things to Debian when they're ready.

Thanks for maintaining this extension - it's very helpful for several of the apps I use.

**Comment by phocean** [comment]
Sure, I should have done it earlier, it is a good practice.
I had been thinking about it, but always postponed. Thank you for asking!

**Comment by phocean** [comment]
Done, tagged version 15, which so far seems to be a stable release.
