### ISSUE TITLE
Raise version numbering for easier transition from topicons

### ISSUE THREAD

**Issue by pacho2** [phocean/TopIcons-plus#38]
Hello

Some distributions (like Gentoo) were packaging the old topicons extension (latest version is 28 for it). Since it became obsolete, we were looking for this extension as replacement and we were thinking about the option of making this one raise the version numbering over the version of the old topicons extension (and, then, starting from 29 as version number). That would be a benefit for us as we could deploy this extension simply as an update of the old one.

What do you think? Thanks a lot

**Comment by phocean** [comment]
Hello,

Thank you for contacting me :-)
I don't feel like it would be a good thing for various reasons, including:
- User confusion. This is a fork, so it became a new project. Some code was kept, but quite a few things also changed. So I don't want it to be packaged as TopIcons, which is unmaintained, but as TopIcons Plus.
- It has already been packaged as-is in a few distribution, including Debian. I don't want to impact them now.
- I would have to rename the whole project as well (github and gnome extension website, where I doubt it is possible), which I feel is too much trouble just for a version number concern.

In fact, I would really appreciate if you package this with its own name.

**Comment by pacho2** [comment]
OK, no problem, we will see how to handle it downstream :)
