### ISSUE TITLE
icons disappear on opacity change

### ISSUE THREAD

**Issue by ghost** [phocean/TopIcons-plus#39]
![screenshot from 2016-10-08 11-53-43](https://cloud.githubusercontent.com/assets/6930157/19211802/e8cd8434-8d4d-11e6-8215-f81c4526256b.png)

**Comment by phocean** [comment]
Hmm well you have to elaborate a LOT more about environment and context.
Otherwise I can tell it is normal if you put opacity=0.
Sorry.
