### ISSUE TITLE
Icon wrong size

### ISSUE THREAD

**Issue by ghost** [phocean/TopIcons-plus#40]
![screenshot from 2016-11-04 18-59-47](https://cloud.githubusercontent.com/assets/6930157/20014736/e88b67a6-a2c0-11e6-95d9-3485fa24bd7b.png)

the icon is Deluge's

debian-testing, GNOME Shell 3.22.1

**Comment by phocean** [comment]
I cannot reproduce the problem, Deluge 1.3.13, Fedora 24, Gnome Shell 3.20.

**Comment by ghost** [comment]
i think it happened to me when Deluge finished downloading a torrent and started blinking to notify.

**Comment by phocean** [comment]
What version of Deluge?
Just completed a download, did not blink (no option for that?) and no issue at all.
How did you install TopIcons (debian repo/github/extension website)?

**Comment by ghost** [comment]
deluge: 1.3.13, installed from gnome extensions website,
blinking is the default behavior when a download finishes and Deluge is minimized or in the background.

**Comment by phocean** [comment]
Found the option, but it is not by default: you need to enable the "notification" module and then enable the blinking options in the new Notifications category.

But then, the "blinking" option is grayed out for me, so I cannot enable it. No idea why and not sure it is worth debugging on the TopIcons side. Do you have the issue with the legacy tray?

**Comment by ghost** [comment]
I cannot find the option you're talking about, it was the default behavior when i installed Deluge. 
I cannot reproduce this with the legacy tray yet.

**Comment by phocean** [comment]
See:

![capture d ecran de 2016-11-06 15-25-08](https://cloud.githubusercontent.com/assets/4280885/20038499/40b3f054-a435-11e6-8d34-e4124a764ee8.png)
![capture d ecran de 2016-11-06 15-24-49](https://cloud.githubusercontent.com/assets/4280885/20038502/43bef078-a435-11e6-86e2-e11b2c1f7c0e.png)

If we have the same version but it is different, I can't help. Anyway, considering status icons are going to be dropped in Gnome, I don't think I will invest much time on this.

**Comment by ghost** [comment]
yeah that's strange, same version different options
![screenshot from 2016-11-06 16-35-33](https://cloud.githubusercontent.com/assets/6930157/20038594/284fa18e-a43f-11e6-8dea-32ac6f4c1e1a.png)

alright then, let's not spend more time on this.
