### ISSUE TITLE
installation error missing metadata

### ISSUE THREAD

**Issue by rickmed** [phocean/TopIcons-plus#43]
Tried to install from firefox (gnome 3.20). Got this:

"JS ERROR: Could not load extension TopIcons@phocean.net: Error: Missing metadata.json"

**Comment by phocean** [comment]
Do you mean that you installed it from there:

https://extensions.gnome.org/extension/1031/topicons/

I am surprised because it is impossible for a submission with missing files to the gnome extension website to get validated with missing files (like metadata.json). Also, I have got no other reports. from there.

**Comment by rickmed** [comment]
@phocean well, that was the only way I tried to install it so...¯\_(ツ)_/¯. Just to be clear, the error was on running gnome-shell --replace on the console while installing the extension from the website.

**Comment by phocean** [comment]
Look, the file is there:

![capture d ecran de 2016-12-14 14-20-05](https://cloud.githubusercontent.com/assets/4280885/21183497/7d320e76-c208-11e6-875d-46782e5a01cf.png)

So there is no apparent reason for your installation to fail.

I don't know what got wrong on their side, it is rather a bug for them or something wrong locally (your browser).
You can check if the file got download there:

`ls -la ~/.local/share/gnome-shell/extensions/TopIcons@phocean.net/metadata.json`

Clean the folder and restart, just in case.

Anyway, as it is painfully slow to get submission validated there, I will wait for the next release (with bug fixes) before re-uploading there.

**Comment by rickmed** [comment]
I removed the folder, reinstalled and it worked. Thanks!
