### ISSUE TITLE
Skype Integration legacy icon removal sometimes fail

### ISSUE THREAD

**Issue by ronjouch** [phocean/TopIcons-plus#45]
I use TopIcons-plus as well as [Skype Integration](https://extensions.gnome.org/extension/696/skype-integration/), which has a feature that was broken by TopIcons-plus commit b3321279 "add center position". The now-broken feature is that Skype-Integration can hide Skype's legacy tray icon (because it adds a GNOME HIG-compliant indicator). So, being unable to hide the legacy tray icon and adding a new modern indicator nevertheless, I end up with two Skype "top-right icons": the legacy, and the modern one.

Looking at recent changes, it looks like [this line of TopIcons-plus b3321279 ](https://github.com/phocean/TopIcons-plus/commit/b3321279977f3a7e06ebb2434bb92eb2f478afbe#diff-06f1274e40de25abda72d812b1cce86aR252) is the culprit: it changes the icon `wm_class` with:

```js
let wmClass = icon.wm_class ? icon.wm_class.toLowerCase() : '';
```

... so `"Skype"` → `"skype"`. Unfortunately, Skype-Integration legacy-icon hiding function [checks on the capitalized `"Skype"` string](https://github.com/chrisss404/gnome-shell-ext-SkypeNotification/blob/73b65d02dafda3da4ed50a0f90fac7b676e3dd68/SkypeNotification%40chrisss404.gmail.com/skype.js#L861):

```js
if(this._skypeHideOriginalTrayIcon && icon.wm_class == "Skype") {
```

→ I'd propose a patch removing this call to `.toLowerCase()`, but looking at b3321279 I fail to understand why it's necessary in the first place. Is it / can we remove it? *(Note: looking at the commit, I realize this `wm_class` de-capitalization code is not new, it was just extracted into a function. Anyway, maybe the class-changing was happening later / less frequently before b3321279 or some changed logic now causes a race between TopIcons-plus and Skype-Integration; whatever: the end result is that I never had this problem until upgrading TopIcons-plus a few days ago, and now it's apparent)*

Thanks for the continued maintenance of the extension :)

**Comment by phocean** [comment]
Hello,

Thank you for the report.
I am using Skype version 4.3.0.37 and it works as expected. And I don't understand how the change I made would have some impact on this.

To clarify:

- TopIcons **does not** change wmClass, it hides Skype icon when the Skype integration extension is enable. What you see in the code in just a local variable allocation, in no way it is changing anything on the Skype window.

- It is normal that the code uncapitalises wmClass before it is compared with the blacklist. Not necessary but just to be safe.

- Skype integration extension also has an option to hide the tray based on "Skype" string.
So both features are partially redondant, but TopIcons covers more wmClass string cases.

I believe for some reason your wmClass is not exactly Skype.
What version of Skype are you using ?

**Comment by phocean** [comment]
After starting Skype, could you give me the output of:

`%  xprop | grep WM_CLASS`

You will have to select the Skype contact window when the cross cursor shows up.

**Comment by ronjouch** [comment]
@phocean 

> TopIcons does not change wmClass, it hides Skype icon when the Skype integration extension is enable. What you see in the code in just a local variable allocation, in no way it is changing anything on the Skype window.

True, sorry; I did a quick parse/blame of recent commits and stumbled on this line but I didn't read what was done with it. So let me "de-pinpoint" my incorrect conclusion to a broader regression statement:

* Since I updated TopIcons-Plus on December 23, Skype-Integration fails to destroy the legacy icon (whose features are replaced/re-implemented with a proper Shell indicator), resulting into a duplicate Skype icon:  
![topicons-skypeintegration-dup](https://cloud.githubusercontent.com/assets/522085/21472535/a643a470-caad-11e6-9141-cb6298350c57.png)
* Bug appears when *starting Skype*. If then I restart Shell (`Alt`+`F2`, `r`), then the legacy icon is properly destroyed:  
![topicons-skypeintegration-afterrestart](https://cloud.githubusercontent.com/assets/522085/21472549/07c8077c-caae-11e6-9de5-376638adaebc.png)



> What version of Skype are you using ?

```
~ skype --version              
Skype 4.3.0.37
© 2014 Skype and/or Microsoft
```

> What does `xprop | grep WM_CLASS` return?

```
~ xprop | grep WM_CLASS
WM_CLASS(STRING) = "skype", "Skype"
```

**Comment by phocean** [comment]
Ok, thank you for the detailed information. ;-)

I could reproduce the issue myself, but only once in a while. The cause is quite obscure to me, I have to investigate.

**Comment by ronjouch** [comment]
One more thing: in the same timeframe (so maybe due to the same changes?), other applications started to fail to be TopIcon-ified. For example, [Transmission](https://transmissionbt.com/) doesn't get its TopIcon, and I have to restart Shell (`Alt+F2`, `r`) to get it. I can create a new bug if you think these are two separate problems.

**Comment by phocean** [comment]
About Transmission, I have the same issue with the legacy tray (Gnome one, TopIcons disabled). I just check on two different machines, could you also check again?
Unfortunately, the extension cannot address such issues. Such breakages should be expected more and more as Gnome tries its best to make it obsolete.
It should be reported to either Gnome or Transmission (in a way that they should bring support to the notification infrastructure).

**Comment by phocean** [comment]
EDIT: Ignore more or less my previous answer if you got it.

Again weirdness: on my 2 test machines, I can reproduce it only on Wayland and with either the legacy tray (Gnome on) or the topicons extension.
On Xorg, it works without any problem.

It is strange because, if you can reload, it means you are on Xorg.

Have you tried with the legacy tray only?

**Comment by phocean** [comment]
It could be related to #42, by the way.

**Comment by ronjouch** [comment]
@phocean 
> It could be related to #42, by the way.

Indeed. Thanks.

> It is strange because, if you can reload, it means you are on Xorg.

Yes I am running Xorg, I blacklisted Wayland because I need X for a few X-only tools I use (`wmctrl`, `xdotool`, `autokey`) with no Wayland equivalent as far as I know :-/ .

> Have you tried with the legacy tray only?

If that's what you mean, I just tried disabling TopIcons (i.e. leaving Shell do its bottom-left corner job), and I couldn't get the Transmission icon to disappear like it happens with TopIcons; everything seems okay: Transmission's icon is always present in the bottom-left tray.

**Comment by phocean** [comment]
see issue #47 for Transmission, sorry but it is not something we can fix.

**Comment by phocean** [comment]
I pushed a fix attempt on the dev branch. And, wow, that was a stupid and obvious mistake of mine.

So far it is working for me, could you please test as well?

**Comment by ronjouch** [comment]
> I pushed a fix attempt on the dev branch. And, wow, that was a stupid and obvious mistake of mine. So far it is working for me, could you please test as well?

@phocean seems to work fine here too; closing this bug, will re-open if I run into problems. Thanks for the fix!
