### ISSUE TITLE
Doesn't works with last update

### ISSUE THREAD

**Issue by SalahAdDin** [phocean/TopIcons-plus#46]
In this momment doesn't works, i try install, and yes, install, but when i go to installed extensions, this extension isn't there.
![captura de pantalla de 2016-12-30 00-53-44](https://cloud.githubusercontent.com/assets/5034215/21555995/c34cc8be-ce25-11e6-9fbf-8e6e2f81cd3a.png)

**Comment by phocean** [comment]
Hi,
I am not responsible for outages there, you should contact the gnome project.
I only upload there the same file as here, and that is validated.
I can see the issue must have been fixed as there have been several user feedbacks since then.
