### ISSUE TITLE
Quitting Skype through Skype Integration crashes TopIcons-plus

### ISSUE THREAD

**Issue by shihrer** [phocean/TopIcons-plus#48]
If I quit Skype through Skype Integration, topicons disappears and I have to restart gnome-shell to get them back.

**Comment by phocean** [comment]
This has been tested. So what distro, logs, etc. ?

**Comment by shihrer** [comment]
I'm on Fedora 25.  Where do I find the logs?

**Comment by phocean** [comment]
I am actually waiting to see what will be going on with the skype extension, as Skype is going to block the older client and the alpha version is the future.
I don't want to spend time testing with an extension that may become obsolete.

**Comment by shihrer** [comment]
Yeah, that's fair.  I know they're supposed to disable older versions of Skype in March but have you seen any confirmation that it includes Skype for Linux?  Last I saw, it was more speculation.  Would be interesting to see MS disable their "stable" client for an alpha.

**Comment by phocean** [comment]
As stated by the author:

https://github.com/chrisss404/gnome-shell-ext-SkypeNotification

Sadly, there is no more API available to allow the extension to work.

So I will drop the support as well and remove the unnecessary code.
