### ISSUE TITLE
Loss hovering effect after upgrading to v19

### ISSUE THREAD

**Issue by kminh** [phocean/TopIcons-plus#49]
Hi,

Thank you very much for this extension, a must-have for Gnome!

After upgrading to v19, it seems that hovering on the icons no longer change the opacity to 255, see commit https://github.com/phocean/TopIcons-plus/commit/67dc6b1aa27a69ec546cc8d01676020434c2196d#diff-06f1274e40de25abda72d812b1cce86aL248

Using v17, I can set the opacity to something lower than 255 (for example 220), so when I hover an icon, I get a nice little feedback because opacity is changed to 255. Could you please advise if this was removed on purpose? Is there a way to get this back?

Thank you.

**Comment by phocean** [comment]
Hi,
Thank you for your support, it is always very encouraging ! :-)
I had simply never been aware of the hovering stuff and thus never cared.
It is probably a setting in GTK, so I will look at it.

**Comment by phocean** [comment]
The last update should make you happy ;-)
