### ISSUE TITLE
'.. a stop job is running..' // gnome.shell did not shutdown properly 

### ISSUE THREAD

**Issue by ghost** [phocean/TopIcons-plus#50]
dont know why ( and i didnt digg deep), but with this extension enabled my system cant shutdown properly.
im on Debian SID btw

**Comment by phocean** [comment]
Very unlikely to have a point with this extension.

**Comment by kasette** [comment]
yy, ure right. im also on SID. This was more FYI. Maybe there will be more ppl in future who notify this cause something changed =)
