### ISSUE TITLE
Error on Gnome 3.24 beta

### ISSUE THREAD

**Issue by sinhn-zz** [phocean/TopIcons-plus#51]
I am trial the Gnome 3.24 beta (3.23.90) -- Is this error a bug of Gnome or the change in structure that affect this extension?

Thanks for great extension!
```
TypeError: redeclaration of let hbox

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
```

**Comment by phocean** [comment]
Hi,

Thank you for reporting. Indeed, something has changed and is more "strict".

I cannot test these next days (lack of time and no Gnome 24 box), but the fix I pushed in the dev branch should work.
I just made cleaner variable declarations.

Could you pull the dev branch and test ? Let me know if you need help for this procedure.
The issue was in the preferences, so please make sure that the option dialog opens and works.

**Comment by dino99** [comment]
hi phocean,
i'm affected as Ubuntu Zesty now has moved to gnome-shell 3.23.90 (3.24). 

GNOME Shell 3.24 now uses mozjs38 (SpiderMonkey 38) which has stricter syntax rules.
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey

Im ready to test your tweak if you point me to the good place for making the change.

**Comment by phocean** [comment]
Thanks, so, if you don't have it, first clone the repo:

```
git clone https://github.com/phocean/TopIcons-plus.git
```
Or just `git pull` from the existing repo.

Then switch to dev:

```
git checkout dev
make
```

Reload Gnome (Xorg: alt-f2 / r) or login/logout (Wayland) and you are done.

**Comment by dino99** [comment]
Thanks for the quick answer
Some good news, but not enough:

oem@u64:~/TopIcons-plus$ make
glib-compile-schemas schemas
rm -rf _build
mkdir _build
cp -r schemas convenience.js extension.js metadata.json prefs.js README.md _build
echo Build was successfull 
Build was successfull
rm -rf ~/.local/share/gnome-shell/extensions/TopIcons@phocean.net
mkdir -p ~/.local/share/gnome-shell/extensions/TopIcons@phocean.net
cp -r _build/* ~/.local/share/gnome-shell/extensions/TopIcons@phocean.net
rm -rf _build
echo Installed in ~/.local/share/gnome-shell/extensions/TopIcons@phocean.net
Installed in /home/oem/.local/share/gnome-shell/extensions/TopIcons@phocean.net

Reload gnome-shell done
So now:
- gnome-tweak-tool : still get a triangle error flag; on/off switch not usable
- extensions.gnome.org/... still show a red "error" flag

**Comment by phocean** [comment]
Then, I will have to investigate more. I will need the log from journalctl.

Sorry but it is the worst timing for me, I cannot look at it before the next 10 days.

**Comment by dino99** [comment]
journalctl does not give much details:

journalctl | grep TopIcons
Feb 18 09:56:38 u64 gnome-shell[3092]: Extension TopIcons@phocean.net already installed in /home/oem/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
Feb 18 09:57:43 u64 gnome-shell-ext[11609]: JS LOG: Extension TopIcons@phocean.net already installed in /home/oem/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded

**Comment by dino99** [comment]
Tried to join a file by drag & drop, but that open a severe security issue: this create a extern link to my hdd (free worldwide access; oh my god) instead of loading that file here. So removed that link.

**Comment by phocean** [comment]
Please make sure to uninstall any other instance of the extension. The presence of files in /usr/share/gnome-shell/extensions/ indicates that it was installed as root, probably from a package.
Uninstall everything, log in/log out, reinstall from the source and log in/log out again.

I am not saying it will solve the issue, but we have to make things clear.

Otherwise, I am surprised by your statement. Github cannot open access to local files. The drag&drop simply uploads files.

**Comment by greatquux** [comment]
Just confirming same thing happens here. Uninstalled extension, checked out dev branch, installed, and can get the prefs window up in gnome-tweak-tools but still have triangle icon and can't load it.  I did 'gnome-shell --replace' from a command line and don't see anything about TopIcons either in the text (I copied and pasted it all to an editor and searched for TopIcons.) 

Perhaps it needs to be explicitly declared as compatible with 3.24?

**Comment by phocean** [comment]
Thank you! I really need to install a test box and debug it.

By the way, I am pretty sure it is not due to the version declaration, as checks have been disabled with Gnome 3.22.
Anyway, you can verify it quickly by editing the metadata.json file.

**Comment by shenki** [comment]
I tested your dev branch on my Ubuntu system and it was still broken. I came up with a fix that works for me:

https://github.com/phocean/TopIcons-plus/pull/55

**Comment by dino99** [comment]
Thanks shenki for the working tweak: no more error from gnome-tweak-tool; but still refuse to be loaded.

**Comment by shenki** [comment]
@dino99 you need to uninstall the system version as @phocean explained

**Comment by greatquux** [comment]
It works! Please update dev branch to include fix. I modified myself since I don't know how to use git very well. :) Wouldn't it have been great if somewhere in the error output 'TopIcons' was mentioned somewhere? Anywhere? (Not that it's your fault, I'm just saying it would have helped everyone.)

**Comment by phocean** [comment]
dev branch updated. Can someone please test and confirm again?

**Comment by V3XATI0N** [comment]
I can confirm this works for me on 3.24 beta. Awesome!

**Comment by greatquux** [comment]
has the version on https://extensions.gnome.org been updated?  i tried to install from there just to be on the stable auto-updated train again but it tries to install and then doesn't.

**Comment by phocean** [comment]
Sure it has, so I guess there is an issue there.

**Comment by greatquux** [comment]
yeah probably - can't seem to install any extensions now (sigh). it'll be fine i'm sure in a month when the bugs are squashed.

**Comment by phocean** [comment]
Yes, I am having a lot of issues too. This website is not reliable at all :-(

**Comment by dino99** [comment]
Got a new version from the ubuntu archive:
gnome-shell-extension-top-icons-plus (20-1) experimental; urgency=medium

  * New upstream release
  * Bump debhelper compat level to 10

 -- Simon McVittie <smcv@debian.org>  Mon, 13 Mar 2017 08:42:05 +0000

Now that extension does not output warning/error. But only the active app has his icon displayed. Looks like all the icons are displayed in the same place, instead of getting displayed separated.

**Comment by phocean** [comment]
I will wait for the Gnome 24 official release before debugging it.
There are too many wired things for a very simple extension and no time to play with unstable software.
