### ISSUE TITLE
Icon(s) invisible when GNOME Shell Magnifier (Zoom) enabled

### ISSUE THREAD

**Issue by errestan** [phocean/TopIcons-plus#53]
To reproduce:
1.  When a try icon is visible, enable the magnifier with the keyboard command Supper + Alt + 8.
2.  Scroll to the top panel and observer the icons are invisible but can still be interacted with.

GNOME version 3.22.3.

Tested on multiple machines with both Intel and NVIDIA graphics under X and Wayland.

**Comment by phocean** [comment]
Yes, reproduced. Thanks for letting me know.

**Comment by phocean** [comment]
After testing, it works beautifully now. It was presumably a gnome-shell issue.
