### ISSUE TITLE
Update installation instructions.

### ISSUE THREAD

**Issue by audreytoskin** [phocean/TopIcons-plus#54]
The README could use some updating.

For example, it offers a long list of shell commands that I think is unnecessary, since you have a Makefile.

Also, I think the note about disabling the GNOME Shell version compatibility check in gsettings might be obsolete. Shell version compatibility checks are [disabled by default as of GNOME 3.22](https://git.gnome.org/browse/gnome-shell/commit?id=5e0e3edc7be44c9e370604f1d3514efc37e68a94) (this link actually appears in the gsettings paragraph). And `metadata.json` explicitly states compatibility with all versions of GNOME as far back as 3.16. So it seems to me that keeping the compatibility check is a good thing for even older versions of GNOME, and disabling the check is unnecessary for newer versions... Unless TopIcons Plus would actually work with versions of GNOME before 3.16.

If you agree, I can take care of these rewrites for you, if you like.

**Comment by phocean** [comment]
Sure, it has been a long overdue I am always postponing. :-(
If you can push a merge request with some changes, I would happily review and accept it.

Thank you! :-)

**Comment by audreytoskin** [comment]
the credits section provides a link for the original TopIcons extension, but [the URL no longer works](http://94.247.144.115/repo/topicons). It's an IP address rather than a domain name. It responds to ping, but does not respond to my web browser at all, not even a 404 or 501 or whatever.

**Comment by audreytoskin** [comment]
...Is there an alternate domain we could use?

**Comment by phocean** [comment]
No, the original author has not given any sign of life for years. I could never contact him.
That is actually the main reason of my fork.
So let's just remove the URL.

**Comment by audreytoskin** [comment]
Okay, done.

Two more points:

1. The changelog is out of date too, but it also only has notes about one release. Is this something that we want to update too, or should it just be removed?
2. I can't really comment on the Known Issues section, since I haven't used Dropbox in a long time. I could install Dropbox for the purpose of testing its Legacy Tray icon, but if you already use Dropbox, it would be easier if you did it.

**Comment by phocean** [comment]
Great :-)

1. No, it was created before I start using github releases. Now the chanlog can be found in the releases. Let's remove it.
2. I haven't had any issue with Dropbox anymore, so let's remove it too. Instead, I would refer put the GDK_BACKEND tip and point to issue #47, as it is something that will happen more and more with a growing Wayland user base.

**Comment by phocean** [comment]
Thank you @terrycloth !
