### ISSUE TITLE
TopIcons doesn't run with gnome-shell 3.23.91

### ISSUE THREAD

**Issue by frandieguez** [phocean/TopIcons-plus#58]
I'm using Archlinux and the latest gnome-shell from the repository below:

`[gnome-devel]
Server = http://softwareperonista.com.ar/repo/archlinux/gnome-devel/x86_64
SigLevel = Never`

The thing is that the extension doesn't start when running with the dev version of gnome-shell (upcoming 3.24) and if I try to go to its preferences dialog the next error raises:

`TypeError: redeclaration of let hbox

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49`

Not sure how I can get a log from the extension startup to paste here.

Regards.

**Comment by phocean** [comment]
Hi,
It was fixed with #51.
You are not using an up-to-date extension. Where does it come from?
Please try with the github version. There is no "hbox" anymore.

**Comment by frandieguez** [comment]
I'm using the version from extensions.gnome.org. i'll install it from the repository.

Should I use the dev branch or master?

**Comment by phocean** [comment]
The master is safer, even though there is not much difference at this time.

The gnome website is so bad that I am considering to stop uploading there (I did push the fixed version however).

**Comment by phocean** [comment]
Closing it, reopen if this happens again by any mean.

**Comment by frandieguez** [comment]
Installed from master branch, now works perfectly.

Thanks!
