### ISSUE TITLE
TopIcons Plus increases noticeably the load time of the desktop

### ISSUE THREAD

**Issue by somas95** [phocean/TopIcons-plus#60]
System: ArchLinux (with the last updated installed) 
Gnome 3.22 
Start-Up Applications: variety, plank, redshift and dropbox 

Possible causes: 
Misconfigurations, but I reinstalled the extension. 
Maybe the extension waits to the programs that will display an icon in the tray to load, causing a bottleneck, but I don't know. 
If I can help in any way, I'll do it

**Comment by phocean** [comment]
No, the extension relies 100% on the Gnome API, it has no loop and is not waiting for anything.
It just takes icons and move them to the top, purely in UI, without interfering with the gnome-shell logic.

Before I investigate further and install software I do not use and even know (variety, plank), can you try to boot with them disabled ? All disabled and then one by one ?

At least we need to isolate the faulty program.

**Comment by somas95** [comment]
Well, that's weird. Now the system starts well. I was pretty sure of the mentioned "bug", as I ran a lot of tests before pointing to any program, trying to isolate the issue. It's difficult to debug a gnome start-up, so that didn't help. My apologies for all this inconvenience, I don't understand what happened, but is resolved. Thanks for your attention

**Comment by phocean** [comment]
No problem, you are welcome.
