### ISSUE TITLE
[query] Would "Dash Icons" be in scope/feasible?

### ISSUE THREAD

**Issue by lofidevops** [phocean/TopIcons-plus#62]
I would prefer my legacy tray icons to appear in the dash, rather than the top bar. Is this feasible as an option for this extension, or any extension?

I suspect the biggest issue would be losing whatever right-click functionality the tray icon has. I wouldn't mind losing it, or launching it through a menu option on the dash icon.

**Comment by phocean** [comment]
Sorry but it will not happen for the following reasons:

1. I am not convinced by the usability and the popularity of such a feature. After all, Gnome has a rather empty top bar, let's make some use of that pixels. It is also where most people expect a systray or anything similar. 

2. The feasibility is not certain. Even then, many issues are to be expected.

3. As I already pointed out in other places, Gnome is simply dropping support for any system tray. It is already quite buggy and is going to be worse. I will not invest massive (in my perspective) coding time for something that is already dead. Topicons is just here to ease the transition.  The future is the Gnome notification system, and I think it is very cool and will push for better application architectures (even though it will take time before all applications get there).

**Comment by lofidevops** [comment]
Thanks for the insights!
