### ISSUE TITLE
Icons unclickable when in "Activities" mode.

### ISSUE THREAD

**Issue by vmavromatis** [phocean/TopIcons-plus#63]
Extension works normally, but when I enter "Activities" mode (windows button), I cannot right-click icons. Tested on GNOME 3.22 and 3.24.1 Manjaro. Apps tested were Manjaro updater and Skype.

**Comment by phocean** [comment]
Classified as potential enhancement, not a bug, as it is not supported by the legacy tray.
Feasibility with gnome-shell to be studied...

**Comment by ghost** [comment]
In case this helps, it is possible with this GNOME Shell Extension: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by phocean** [comment]
In recent versions, icons are clickables when the app designer made the icon to open the main window.

However, it would not work when it's a menu.

So it kind of works now... and regarding to the menu, honestly, I doubt it can be made and would not bother for the limited use case.
