### ISSUE TITLE
Language localization

### ISSUE THREAD

**Issue by amivaleo** [phocean/TopIcons-plus#64]
Hi!
Can you localize you extension in different languages? The settings are only shown in english. I would like to help translating into italian languages but I can't see where to add .po and .mo files.

Thanks for you attention. :)

**Comment by phocean** [comment]
Hi,
Sure, that would be nice.
I am not sure that po files are needed, I believe there is already an API in gnome-shell.
I don't know how to do for now, if you have more info I take it :-)
Thanks.

**Comment by AlexGluck** [comment]
I help with russian translation.

**Comment by AlexGluck** [comment]
Update extension in extensions.gnome.org and close please issue.

**Comment by phocean** [comment]
@amivaleo as you can see there is now German and Russian translations in the master branch.

It would be cool if you are still willing to translate it in Italian !

I am closing it, looking forward to seeing your merge request ;-)

**Comment by amivaleo** [comment]
I'm on it! ;)

**Comment by phocean** [comment]
Hi guys,

I have a question for you : does the translation really works for you ?

I tried to translate it into French myself, but the settings keep staying in English.
So I wonder if it is a problem with the code (I reviewed it multiple times) or if it is just my environment.

Gnome documentation on the topic is sparse:

https://wiki.gnome.org/Projects/GnomeShell/Extensions/FAQ/CreatingExtensions

I reviewed many other extensions and their code is not really different than mine.

So any trick on how to test is welcome.

**Comment by AlexGluck** [comment]
Latest version from extensions.gnome.org does not have translation. How to test this idk, sorry.

**Comment by amivaleo** [comment]
I've just downloaded the code from the master branch and yes, it's translated in italian.
![image](https://user-images.githubusercontent.com/24316547/30520834-88becdf6-9bb5-11e7-856e-db85b251fe09.png)
I use gnome-shell 3.20.4.

**Comment by phocean** [comment]
@amivaleo thanks, nice to see it working :-)

@AlexGluck No problem. You could `git clone` the version from here and `make install`, but anyway I am going to make a release very soon.

It is just that I am concerned to no being able to test it myself :-/

**Comment by phocean** [comment]
Never mind, I found the issue.

I was not aware that naming the po file with the same name as the extension was important.

So it is all fine...

Thanks !

**Comment by amivaleo** [comment]
You're welcome. :)
