### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Francewhoa** [phocean/TopIcons-plus#65]
Hi there :) 

What are the requirements for this extension? extensions.gnome.org says it's incompatible with Debian 8 Jessie with GNOME 3.14.1

I searched [that documentation](https://github.com/phocean/TopIcons-plus/blob/master/README.md) but found no answer. Also no answer on the extension page at https://extensions.gnome.org/extension/1031/topicons/

**Comment by phocean** [comment]
Hi,

It is in the documentation, right below INSTALLATION:

`TopIcons Plus requires GNOME Shell 3.16 or newer.`

It means it has not been tested with older versions, it might work with some tweaks.

**Comment by Francewhoa** [comment]
Thanks @phocean I missed it
