### ISSUE TITLE
Gnome shell 3.24 compatibility

### ISSUE THREAD

**Issue by ArthurGarnier** [phocean/TopIcons-plus#67]
Hi,

The extention is not compatible with gnome-shell 3.24

  "shell-version": [
    "3.16",
    "3.18",
    "3.20",
    "3.22",
    "3.21.91"
  ],

And Gnome Shell tweak show an error : ![](https://img.agfr.ovh/zLdels)

**Comment by phocean** [comment]
Hi,

About compatibility : I have had many similar reports : Gnome does not check versions anymore, so it is not incompatible.

About the error : what it shows is that you are using a very old version (for instance, no more "hbox"). Please update, problem fixed.

**Comment by ArthurGarnier** [comment]
Mea culpa, it was outdated. Thanks !
