### ISSUE TITLE
Opening an application is Gnome Dashboards works wrongly

### ISSUE THREAD

**Issue by vporton** [phocean/TopIcons-plus#68]
I have KTimeTracker with a tray icon running.

When in Gnome Dashboard (I mean that screen with small windows to switch windows and launch programs easily), clicking the KTimeTracker icon opens the KTimeTracker window, but the window is not brought to foreground. Instead the window appears in the Dashboard. When clicking an icon while in Dashboard mode, we need automatically exit from Dashboard mode and show the window.

It is not specific to KTimeTracker. For example, I have the same bug with Skype.

**Comment by phocean** [comment]
It is not clear to me, especially as I don't have any issue with Skype.

Your description sounds it is more related to the dashboard, not topicons...

**Comment by vporton** [comment]
I propose the following simple thing:

Exit from the Dashboard when any tray is clicked.

**Comment by phocean** [comment]
1. It is already the case with most programs

2. The systray behavior is up to the application author responsibility. Which leads to inconsistent designs, and that is precisely why Gnome-shell is basically killing the systray to the profit of the notification subsystem.

3. Do not address such concerns to any gnome extension like topicons (moreover, topicons is simply moving the tray to the top, it is not messing with the dashboard). There is nothing that we can do.
Address such issues to the Gnome project or/and to each application author.
