### ISSUE TITLE
Fails to load in 3.26 beta (3.25.90)

### ISSUE THREAD

**Issue by benjamindaines** [phocean/TopIcons-plus#75]
Extension fails to load, no errors reported in looking glass.

**Comment by phocean** [comment]
There is a discussion on reddit:

https://www.reddit.com/r/gnome/comments/6ubtvj/question_regarding_the_removal_of_the_legacy/

There is a patch for the old extension, so it needs some work to merge it with our code:

https://gist.github.com/fmuellner/e1aaec3169990fa7b7bd95da4e0a915a

Too busy with my job to do it this week, however :-(

**Comment by fmuellner** [comment]
I opened #78 with a proposed fix.

**Comment by phocean** [comment]
Dear all, I am closing it as it should be fixed thanks to @fmuellner.

Feel free to re-open if there is any issue.
