### ISSUE TITLE
Hide Skype Tray Icon If Skype Integration Extension is Active

### ISSUE THREAD

**Issue by chrisss404** [phocean/TopIcons-plus#8]
When both extensions, TopIcons and Skype Integration, are enabled at the same time, users have two Skype icons in Gnome Shell's top bar. Therefore users of the Skype Integration extension wish to get rid of the original tray icon, which can be accomplished fairly easily, see: [#58](https://github.com/chrisss404/gnome-shell-ext-SkypeNotification/issues/58) (tested with ag's TopIcons extension).

Do you think the incorporation of a similar code snippet as proposed in the mentioned issue makes sense?

Kind regards

**Comment by phocean** [comment]
Done, but with a simpler and more stable approach than there.

Note however that there is a caveat: the extension cannot tell when the Skype extension has been enable at runtime, so you have to reload Gnome-shell or disable/enable TopIcons Plus.

AFAIK, there is no solution as it is out of question to poll and there should not be any signal between extension. At least it is what I presume in the absence of documentation, but maybe someone more knowledgeable will prove me wrong.

**Comment by chrisss404** [comment]
Thx, your implementation is fine. I would also omit the polling approach, as the use case you described is very rare.

However, if the Skype extension is not installed the following error occurs:

```
(gnome-shell:4931): Gjs-WARNING **: JS ERROR: TypeError: imports.misc.extensionUtils.extensions[blacklist[i][1]] is undefined
onTrayIconAdded@/home/chris/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:92
moveToTop@/home/chris/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:172
```

**Comment by phocean** [comment]
yes, I was stupid not to think about it, thanks for spotting.
I just did a quick fix, I will improve it later because I have no time today. Thanks a lot for everything!

**Comment by rockon999** [comment]
Hi! I don't know if you're still interested, but extensions can monitor when other extensions are disabled/enabled.

`const EXTENSION_SCHEMA = 'org.gnome.shell';

/* This should never fail, but let's be careful */

try {
    let schemaObj = Convenience.getSchemaObj(EXTENSION_SCHEMA, true);
    if (schemaObj) {
        this._extension_settings = new Gio.Settings({
            settings_schema: schemaObj
        });
    }
} catch (error) {
    log('Failed to find Gnome Shell settings.');
}

if (this._extension_settings) {
    this._extensionsChangedSig = this._extension_settings.connect('changed::enabled-extensions', Lang.bind(this, [function]));
}`
