### ISSUE TITLE
[Feature] Put buttons inside panel

### ISSUE THREAD

**Issue by SalahAdDin** [phocean/TopIcons-plus#9]
Hi guys, i like this fork, now we can report bugs :D 

I have a problem with Guake icon inside Gnome:
![seleccion_113](https://cloud.githubusercontent.com/assets/5034215/13026561/e29bc7b6-d1f9-11e5-9c2d-4be34c42df84.png)
It hasn't padding or margin, so, it seems ugly.

But in Budgie i have this: 
![seleccion_112](https://cloud.githubusercontent.com/assets/5034215/13026565/081eebd0-d1fa-11e5-9754-11677db1aabb.png)
No problem with guake icon, i think that the top icons are in a panel.

Can you do anything with this? Thanks.

**Comment by phocean** [comment]
Hi, and thanks for the feedback :-)

I am not sure, because the issue is also there in the Gnome legacy tray.
You made me discover Budgie, it seems like there redesigned their own tray.

Anyway, I will make some testing.

**Comment by phocean** [comment]
See : https://github.com/Guake/guake/issues/493
I checked the icon and it has a shadow at the bottom that, I think, explains the shift. On top of that it seems to be ignoring the icons provided by the active global theme.
Changing the whole extension for this single application seems to be overwhelming (especially when, as mentioned there, it is not really necessary and can be hidden).

**Comment by phocean** [comment]
Link to the icon (seems to be hardcoded with the app) :
https://github.com/Guake/guake/blob/master/data/icons/48x48/apps/guake.png

**Comment by SalahAdDin** [comment]
So, we have to report this issue in Guake project?

**Comment by phocean** [comment]
Yes, but the author closed the issue and stopped answering. He does not seem to be willing to fix it.
I doubt that using a panel would solve the issue, anyway the icon is definitely designed that way and must be cropped.
Concerning Budgie, I don't know their approach but they may have simply patched Guake.
You could download the source code of Guake, replace the icon set (by those from Vibrancy, for instance: http://gnome-look.org/content/show.php/Vibrancy+Colors?content=167771) and compile it.
I haven't tried but I am pretty confident that it will work as you expect.

**Comment by phocean** [comment]
Let me know how it goes or if you learn new info, I will help as much as I can regarding the extension.

**Comment by SalahAdDin** [comment]
With the last Guake update this was fixed!

**Comment by phocean** [comment]
Oh, that's very good news! Thanks for the update! :-)
