### ISSUE TITLE
Settings not respected until extension is disabled and then enabled again

### ISSUE THREAD

**Issue by ghost** [phocean/TopIcons-plus#92]
When I log in, the opacity and saturation of the icons is not set to the value that is configured in the extension's settings. If I disable and then re-enable the extension, both are correct again. I believe this happened after I updated gnome-shell.x86_64 to 3.24.3-2.fc26 in Fedora 26, though there were more updates, so I could be wrong.

**Comment by phocean** [comment]
Sorry but I don't think it can be fixed.

See #91 .
