### ISSUE TITLE
Set right alignment as default

### ISSUE THREAD

**Issue by forteller** [phocean/TopIcons-plus#93]
After updating to the latest version my topicons moved from right to center alignment. I also see on the screenshots here on GitHub that the icons there are aligned center. I am convinced that most people will find it more natural and better looking to have the icons clustered together with the other icons on the right hand side than alone in the center besides the clock. Hope you can set right alignment as default!

Thank you very much for this absolutely must have Gnome extension! Your work is immensely appreciated!

**Comment by phocean** [comment]
I did not do this choice arbitrarily.

In my opinion, center looks better as it prevents confusion with shell applets and makes a more balanced view.
I feel it ugly to have all icons on the right, getting close to the clock, and right space empty.

At least, I gave users a choice, unlike gnome developers, so I think it is a non issue.
It is easy to change in the settings.

So I will keep it as is as it expresses my belief of what a better design is. It is a small signature thing that make me feel better :-)
