### ISSUE TITLE
does not work on Ubuntu 17.10

### ISSUE THREAD

**Issue by legluondunet** [phocean/TopIcons-plus#95]
Hello,
I installed Topicons-plus from https://extensions.gnome.org/extension/1031/topicons/?c=33512, install OK, activation OK, but no icons.

Thank you for your help.

Config:
Ubuntu 17.10, gnome on Xorg session, NVidia.

**Comment by jgawlik83** [comment]
This Gnome extensions works with Slack
https://extensions.gnome.org/extension/495/topicons/

**Comment by Albertmoiseev** [comment]
The same thing after the update of the extension... Icons have disappeared ((

**Comment by bpearson** [comment]
I didn't notice at first ( I thought it wasn't fully working ) but its partially working for me. Keepassx icon shows, but others (like Steam and HipChat) do not. Not sure if that helps in any way or not.

**Comment by ghost** [comment]
This has to do with some delay in loading TopIcons plus.

The workaround is to add `X-GNOME-Autostart-Delay=10` (10 is an example) at the end of .desktop files for apps with legacy systray icons in ~/.config/autostart

**Comment by bpearson** [comment]
Steam and Hipchat are not auto starting for me and the icon still doesn't show.

**Comment by ghost** [comment]
Are you sure they are not started. Just check it in a terminal:

`ps -ef | grep -Ei steam\|hipchat`

If they are, it's better to increase `X-GNOME-Autostart-Delay` to e.g. 30

**Comment by bpearson** [comment]
Yes I am sure, I make sure they start only when I want to use them.

**Comment by ghost** [comment]
OK, maybe someone else know a solution.

**Comment by legluondunet** [comment]
launch Steam --> no icon
launch transmission --> no icon
...

**Comment by ghost** [comment]
Are you both running Ubuntu 17.10? I do and did run Ubuntu Gnome 17.04 before that.

I installed `vanilla-gnome-desktop`, so maybe that is the difference.

**Comment by bpearson** [comment]
Thank you! That was it. I previously installed gnome-session in hopes of the old Ubuntu Gnome settings, but this restored much more. The icons are appearing again.

**Comment by legluondunet** [comment]
I use Ubuntu 17.10 for the start of this bug report. I just installed vanilla-gnome-desktop and it works now.

**Comment by legluondunet** [comment]
I close this issue because this extension works with Ubuntu 17.10 if you install gnome vanilla: 
sudo apt-get install vanilla-gnome-default-settings vanilla-gnome-desktop

**Comment by Albertmoiseev** [comment]
Yes, it has started to work. Many thx, mates!

**Comment by ghost** [comment]
@legluondunet With the remark that _when_ applications are started before TopIcon-Plus is started, their icons are not displayed. The workaround is to add a delay (X-GNOME-Autostart-Delay) in the respective ~/.config/autostart/*.desktop files.
