### ISSUE TITLE
High cpu usage if used togerther with SystemMonitor

### ISSUE THREAD

**Issue by sergeG** [phocean/TopIcons-plus#96]
If SystemMonitor is enabled together with TopIcons or TopIconsPlus, then gnome-shell eats one of my cores.

Gnome 3.22, X11, latest extensions from extensions.gnome.org

See also https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/393

**Comment by phocean** [comment]
Yes, but there is nothing I can do, or the other extension can do.
The gnome-shell architecture sucks and is the culprit. It should avoid conflicts and not make it crashy.
Please report such bugs to the Gnome project.
