### ISSUE TITLE
Desaturation does not work with Wayland (after update to 17.10)

### ISSUE THREAD

**Issue by forteller** [phocean/TopIcons-plus#97]
I tried Wayland before updating to 17.10 too, and I think I would have reacted to the icon not being grayscale then. So I'm pretty confident this is new behavior after updating from Ubuntu Gnome 17.04 to Ubuntu 17.10, but I can't be 100% sure.

When logging in with X the Rambox icon is grayscale ![screenshot](https://user-images.githubusercontent.com/343561/31852435-2347cc1c-b667-11e7-983a-a2d507f8438a.png), as it should since I've set Desaturation to 1.0.

But when logging in to the standard session, which now uses Wayland the icon looks like this ![screenshot](https://user-images.githubusercontent.com/343561/31852434-231514b6-b667-11e7-8b51-2ab0fcab3404.png), in full color (which is pretty ugly, but that's Rambox' fault, not yours ;)).

When I tried testing this, going back and forth between X and Wayland a few times the icon once stayed grayscale on Wayland for a little while right after logging in, but then changed back to color. No idea why.

Thanks for a really great extension!

PS: This was an update, not a clean install. I've always had issues with updates before, and I've had a few other minor issues now too, so I might do a clean install. Though it's so much work…

**Comment by phocean** [comment]
Basically, Wayland support for the tray  is non existent in Gnome, so I can do nothing. Sorry...
